safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"

siteTitle: "Commonjava@GitHub"
projectTitle: ""
tagline: "Documentation for Commonjava projects available on GitHub"
owner: "John Casey"
ownerEmail: jdcasey@commonjava.org